# Generated by Django 4.2.5 on 2023-09-20 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KhachHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MAKH", models.CharField(max_length=10, unique=True)),
                ("HOTEN", models.CharField(default="", max_length=100)),
                ("DCHI", models.CharField(default="", max_length=200)),
                ("SODT", models.CharField(default="", max_length=200)),
                ("NGSINH", models.DateField(null=True)),
                ("DOANHSO", models.IntegerField(default=0)),
                ("NGDK", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
