# Generated by Django 4.2.5 on 2023-09-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NhanVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MANV", models.CharField(max_length=10, unique=True)),
                ("HOTEN", models.CharField(default="", max_length=100)),
                ("NGVL", models.DateField(null=True)),
                ("SODT", models.CharField(default="", max_length=20)),
                ("CHUCVU", models.CharField(default="", max_length=20)),
            ],
        ),
    ]
