# Generated by Django 4.2.5 on 2023-09-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoaDon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SOHD", models.CharField(max_length=10, unique=True)),
                ("NGHD", models.DateField(null=True)),
                ("TRIGIA", models.IntegerField(default=0)),
                (
                    "MAKH",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.khachhang",
                    ),
                ),
                (
                    "MANV",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.nhanvien",
                    ),
                ),
            ],
        ),
    ]
